log_level = "warn"


outputs = "All"


position = "Top"
layer = "Overlay"


[modules]
left = [ "Workspaces" ]
center = [ "Tempo" ]
right = [ "SystemInfo", "Settings", "Privacy", "Tray" ]


[workspaces]
visibility_mode = "All"
group_by_monitor = false
enable_workspace_filling = true
disable_special_workspaces = false
max_workspaces = 2
# workspace_names = ["Terminal", "Browser"]


[tempo]
clock_format = "%a %d %b %R"
formats = [
    "%a %d %b %R",         # Mon 23 Dec 14:30
    "%Y-%m-%d %H:%M:%S",   # 2024-12-23 14:30:45
    "%d/%m/%Y %I:%M %p",   # 23/12/2024 02:30 PM
    "%I:%M %p",             # 02:30 PM
    "%A, %B %d, %Y",       # Monday, December 23, 2024
    "%H:%M:%S",            # 14:30:45 (updates every second)
    "%x",                  # Locale date (e.g., 12/23/24)
    "%X",                  # Locale time (e.g., 14:30:45)
]
timezones = ["Asia/Tashkent"]
weather_location = { City = "Tashkent" }


[system_info]
indicators = [ "Cpu", "Memory", "Temperature" ]
interval = 5

[system_info.cpu]
warn_threshold = 60
alert_threshold = 80

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80
sensor = "acpitz temp1"


[settings]
lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"
remove_airplane_btn = true
remove_idle_btn = true
indicators = ["PowerProfile", "Audio", "Microphone", "Bluetooth", "Network", "Vpn", "Battery", "Brightness"]
# battery_format = "IconAndPercentage"
# peripheral_battery_format = "Icon"
# peripheral_indicators = "All" # { Specific = ["Gamepad", "Keyboard"] }
# audio_indicator_format = "IconAndPercentage"
# microphone_indicator_format = "Icon"
# network_indicator_format = "IconAndPercentage"
# bluetooth_indicator_format = "IconAndValue"
# brightness_indicator_format = "IconAndPercentage"


[appearance]
font_name = "JetBrainsMono NF"
scale_factor = 1.0

style = "Gradient" # Islands, Solid, Gradient

opacity = 0.8

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"

workspace_colors = [ "#7aa2f7", "#9ece6a" ]
special_workspace_colors = [ "#7aa2f7", "#9ece6a" ]

# The following are the colors that make up the palette:
#     background_color: Used as the background color for all status bar components
#     primary_color: Used for elements like buttons or slider handles
#     secondary_color: Used for borders and slider tracks
#     success_color: Used for success indicators
#     danger_color: Used for danger messages or danger states
#     (the weak version is used for warning states)
#     text_color: Used as the default text color

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.menu]
opacity = 1.0
backdrop = 1.0
