apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    # Vault server accessible from K3s nodes, CoreDNS won't know about dnsmasq
    server: http://192.168.31.247:8200
    path: pki/sign/poddle-uz
    auth:
      tokenSecretRef:
        name: vault-token
        key: token
        # namespace: cert-manager # This won't work! or ClusterIssuer, cert-manager always looks for secrets in the same namespace where cert-manager is installed (usually cert-manager)
# Alternative: Using Kubernetes auth (more secure for production)
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: vault-issuer-k8s-auth
# spec:
#   vault:
#     server: http://vault.poddle.uz:8200
#     path: pki/sign/poddle-uz
#     auth:
#       kubernetes:
#         role: cert-manager
#         mountPath: /v1/auth/kubernetes
#         secretRef:
#           name: cert-manager-vault-sa-token
#           key: token
